name: "weather"
version: "1.0"
config-version: 2

profile: "weather"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  weather:
    +materialized: view
