weather:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: weather
      schema: staging
      threads: 4
